### ISSUE TITLE
[Auto][es-es] (Aprenda Linux para principiantes: De lo Básico a las Técnicas Avanzadas [Libro Completo])

### ISSUE THREAD

**Issue by RafaelDavisH** [budblack/news-translation-allinone#59]
[Learn Linux for Beginners: From Basics to Advanced Techniques [Full Book]](https://www.freecodecamp.org/news/learn-linux-for-beginners-book-basic-to-advanced/)

**Comment by budblack** [comment]
Oh, you find a bug! I use this logic to pick up LANG_CODE

`const target_lang_code = with_issue_title.match(/\[Auto\]\[(.+)\]/)?.[1] || '';`

You known, this article title incloude `[Libro Completo]`. It takes sth wrong. I'll fix it.

**Comment by budblack** [comment]
[Please goto this issue](https://github.com/budblack/news-translation-allinone/issues/61)
